[build]
  base = "."
  publish = "public"
  command = "gatsby build"
  functions = "functions/build"
  functionsSource = "functions"

[dev] 
 functions = "functions"

[[redirects]]
  from = "https://rateahm.com"
  to = "https://www.myalabamahomemortgage.com/review"
  status = 301
  force = true

[[redirects]]
  from = "https://www.rateahm.com"
  to = "https://www.myalabamahomemortgage.com/review"
  status = 301
  force = true

[[redirects]]
  from = "https://rateahm.com/*"
  to = "https://www.myalabamahomemortgage.com/review"
  status = 301
  force = true

[[redirects]]
  from = "https://www.rateahm.com/*"
  to = "https://www.myalabamahomemortgage.com/review"
  status = 301
  force = true

[[redirects]]
  from = "https://alahomemortgage.com/*"
  to = "https://www.myalabamahomemortgage.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.alahomemortgage.com/*"
  to = "https://www.myalabamahomemortgage.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/review"
  to = "https://search.google.com/local/writereview?placeid=ChIJFYdcrIgh-xQRL4K4TzDkYno"
  status = 301
  force = true